---
- name: Check and deploy Docker container
  hosts: all
  become: true

  tasks:
    - name: Check if container is running
      command: docker ps -q --filter "name=phpapp"
      register: container_check
      failed_when: false
      changed_when: false

    - name: Stop and remove container if running
      command: docker rm -f phpapp
      when: container_check.stdout != ""
   
    - name: Deploy new container
      command: docker run -itd -p 7000:80 --name phpapp tonybas1982/phpapp:v3