---
- name: Deploy Dockerized Application
  hosts: all # Replace 'your_target_host' with the target host or group of hosts where you want to deploy the application.
  become: yes  # This allows Ansible to run commands with elevated privileges (sudo).

  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io  # For Debian/Ubuntu systems. Use "docker" for CentOS/RedHat systems.

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: tonybas1982/phpapp:v5  # Replace with the Docker image you want to deploy
        source: pull

    - name: Check if container is running
      command: docker ps -q --filter "name=phpapp"
      register: container_check
      failed_when: false
      changed_when: false

    - name: Stop and remove container if running
      command: docker rm -f phpapp
      when: container_check.stdout != ""

    - name: Run Docker container
      docker_container:
        name: phpapp
        image: tonybas1982/phpapp:v5 # Replace with the Docker image you want to deploy
        ports:
          - "7000:80"  # Map port 7000 on the host to port 80 inside the container
        restart_policy: unless-stopped  # Automatically restart the container if it stops
